In [1]:
import numpy as np

matrix1 = np.array([[3,2,1],[8,8,1],[3,8,3]])
print(matrix1)

[[3 2 1]
 [8 8 1]
 [3 8 3]]


In [2]:
matrix2 = np.array([[3,2],[6,4]])
print(matrix2)

[[3 2]
 [6 4]]


In [3]:
from scipy import stats

mean = np.mean(matrix1)
median = np.median(matrix1)
mode = stats.mode(matrix1, axis = None)
column_mode = stats.mode(matrix1, axis = 0)
row_mode = stats.mode(matrix1, axis = 1)

print("Mean :: ",mean)
print("Median :: ",median)
print("Mode :: ",mode)
print("Column Mode :: ",column_mode)
print("Row Mode :: ",row_mode)

Mean ::  4.111111111111111
Median ::  3.0
Mode ::  ModeResult(mode=3, count=3)
Column Mode ::  ModeResult(mode=array([3, 8, 1], dtype=int64), count=array([2, 2, 2], dtype=int64))
Row Mode ::  ModeResult(mode=array([1, 8, 3], dtype=int64), count=array([1, 2, 2], dtype=int64))


In [4]:
transpose = np.transpose(matrix1)
print("Transpose of the matrix:\n",transpose)

Transpose of the matrix:
 [[3 8 3]
 [2 8 8]
 [1 1 3]]


In [7]:
determinant = np.linalg.det(matrix1)
print(determinant)

45.999999999999986


In [8]:
if determinant == 0:
    print("The matrix is singular and does not have an inverse.")
else:
    # Calculate the inverse
    inverse = np.linalg.inv(matrix1)
    print("Original Matrix:\n", matrix1)
    print("\nInverse of the Matrix:\n", inverse)

Original Matrix:
 [[3 2 1]
 [8 8 1]
 [3 8 3]]

Inverse of the Matrix:
 [[ 0.34782609  0.04347826 -0.13043478]
 [-0.45652174  0.13043478  0.10869565]
 [ 0.86956522 -0.39130435  0.17391304]]


In [9]:
matrix1 = np.array([[1, 3], [5, 7]])
matrix2 = np.array([[2, 6], [4, 8]])

result = np.dot(matrix1, matrix2)
print("matrix1 x matrix2:\n", result)

matrix1 x matrix2:
 [[14 30]
 [38 86]]


In [10]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print("Vector 1:", v1)
print("Vector 2:", v2)

Vector 1: [1 2 3]
Vector 2: [4 5 6]


In [20]:
addition = v1 + v2
print("Addition:", addition)

subtraction = v1 - v2
print("Subtraction:", subtraction)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]


In [19]:
scalar = 3
scaled_vector = scalar * v1
print("Scalar Multiplication:", scaled_vector)

Scalar Multiplication: [3 6 9]


In [17]:
dot_product = np.dot(v1, v2)
print("Dot Product:", dot_product)

Dot Product: 32


In [18]:
cross_product = np.cross(v1, v2)
print("Cross Product:", cross_product)

Cross Product: [-3  6 -3]


In [21]:
magnitude = np.linalg.norm(v1)
print("Magnitude of v1:", magnitude)

Magnitude of v1: 3.7416573867739413


In [23]:
cos_theta = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
angle = np.arccos(cos_theta)  # Angle in radians
print("Angle between v1 and v2 (radians):", angle)
print("Angle between v1 and v2 (degrees):", np.degrees(angle))

Angle between v1 and v2 (radians): 0.2257261285527342
Angle between v1 and v2 (degrees): 12.933154491899135


In [24]:
elementwise_product = v1 * v2
print("Element-wise Multiplication:", elementwise_product)

Element-wise Multiplication: [ 4 10 18]


In [25]:
projection = (np.dot(v1, v2) / np.linalg.norm(v2)**2) * v2
print("Projection of v1 onto v2:", projection)

Projection of v1 onto v2: [1.66233766 2.07792208 2.49350649]
